name: Publish .tgz to JFrog Artifactory

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:  
            JF_URL: ${{ secrets.JF_URL }}
            JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Set CLI Config
        run: jf npm-config --global=true --repo-resolve=demo-npm --repo-deploy=demo-npm

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://trial9ppsfa.jfrog.io/artifactory/api/npm/npm-repo/

      - name: Locate .tgz file
        id: find-tgz
        run: |
          TGZ_FILE=$(find . -name "*.tgz" | head -n 1)
          if [ -z "$TGZ_FILE" ]; then
            echo "No .tgz file found. Exiting."
            exit 1
          fi
          echo "TGZ_FILE=$TGZ_FILE" >> $GITHUB_ENV

    #   - name: Configure .npmrc for Artifactory
    #     run: |
    #       echo "registry=https://trial9ppsfa.jfrog.io/artifactory/api/npm/npm-repo/" > ~/.npmrc
    #       echo "//trial9ppsfa.jfrog.io/artifactory/api/npm/npm-repo/:_authToken=${{ secrets.JF_ACCESS_TOKEN }}" >> ~/.npmrc
    #       echo "always-auth=true" >> ~/.npmrc

      - name: Publish .tgz to Artifactory
        run: npm publish $TGZ_FILE